/*
 * Copyright (c) Advanced Micro Devices, Inc., or its affiliates.
 *
 * SPDX-License-Identifier: MIT
 */

#include "negative_macros_common.hh"

NEGATE_UNSIGNED_VECTOR_FUNCTIONS(uchar1)
NEGATE_UNSIGNED_VECTOR_FUNCTIONS(uchar2)
NEGATE_UNSIGNED_VECTOR_FUNCTIONS(uchar3)
NEGATE_UNSIGNED_VECTOR_FUNCTIONS(uchar4)
NEGATE_UNSIGNED_VECTOR_FUNCTIONS(ushort1)
NEGATE_UNSIGNED_VECTOR_FUNCTIONS(ushort2)
NEGATE_UNSIGNED_VECTOR_FUNCTIONS(ushort3)
NEGATE_UNSIGNED_VECTOR_FUNCTIONS(ushort4)
NEGATE_UNSIGNED_VECTOR_FUNCTIONS(uint1)
NEGATE_UNSIGNED_VECTOR_FUNCTIONS(uint2)
NEGATE_UNSIGNED_VECTOR_FUNCTIONS(uint3)
NEGATE_UNSIGNED_VECTOR_FUNCTIONS(uint4)
NEGATE_UNSIGNED_VECTOR_FUNCTIONS(ulong1)
NEGATE_UNSIGNED_VECTOR_FUNCTIONS(ulong2)
NEGATE_UNSIGNED_VECTOR_FUNCTIONS(ulong3)
NEGATE_UNSIGNED_VECTOR_FUNCTIONS(ulong4)
NEGATE_UNSIGNED_VECTOR_FUNCTIONS(ulonglong1)
NEGATE_UNSIGNED_VECTOR_FUNCTIONS(ulonglong2)
NEGATE_UNSIGNED_VECTOR_FUNCTIONS(ulonglong3)
NEGATE_UNSIGNED_VECTOR_FUNCTIONS(ulonglong4)
