---
multiproc:
  ChildMalloc: *level_2
  Unit_deviceAllocation_Malloc_MultProcess: *level_2
  Unit_deviceAllocation_New_MultProcess: *level_2
  Unit_deviceAllocation_MallocFree_MultProcess: *level_2
  Unit_deviceAllocation_NewDelete_MultProcess: *level_2
  Unit_hipDeviceGet_MaskedDevices: *level_2
  Unit_hipDeviceGetPCIBusId_MaskedDevices: *level_2
  Unit_hipDeviceGetPCIBusId_CheckPciBusIDWithLspci:
    <<: *level_2
    # Note: no valid pci bdf in wsl
    disabled: [amd_wsl]
  Unit_hipDeviceTotalMem_MaskedDevices: *level_2
  Unit_hipDeviceGetAttribute_MaskedDevices: *level_2
  Unit_hipGetDeviceCount_MaskedDevices: *level_2
  Unit_hipGetDeviceProperties_MaskedDevices: *level_2
  Unit_hipIpcEventHandle_Functional: *level_2
  Unit_hipIpcEventHandle_ParameterValidation: *level_2
  Unit_hipIpcMemAccess_Semaphores:
    <<: *level_2
    # Below tests soft hang in stress test on 13/09/23
    disabled: [amd_wsl]
  Unit_hipIpcMemAccess_ParameterValidation:
    <<: *level_2
    # Below tests fail in stress test on 23/06/23
    disabled: [amd_wsl]
  Unit_hipMalloc_ChildConcurrencyDefaultGpu: *level_2
  Unit_hipMalloc_ChildConcurrencyMultiGpu: *level_2
  Unit_malloc_CoherentTst: *level_2
  Unit_malloc_CoherentTstWthAdvise: *level_2
  Unit_mmap_CoherentTst: *level_2
  Unit_mmap_CoherentTstWthAdvise: *level_2
  Unit_hipHostMalloc_WthEnv0Flg1: *level_2
  Unit_hipHostMalloc_WthEnv0Flg2: *level_2
  Unit_hipHostMalloc_WthEnv0Flg3:
    <<: *level_2
    # Note: CONFIG_NUMA disabled
    disabled: [amd_wsl]
  Unit_hipHostMalloc_WthEnv0Flg4: *level_2
  Unit_hipHostMalloc_WthEnv1: *level_2
  Unit_hipHostMalloc_WthEnv1Flg1: *level_2
  Unit_hipHostMalloc_WthEnv1Flg2: *level_2
  Unit_hipHostMalloc_WthEnv1Flg3:
    <<: *level_2
    # Note: CONFIG_NUMA disabled
    disabled: [amd_wsl]
  Unit_hipMemGetInfo_Functional_Scenario1: *level_2
  Unit_hipMemGetInfo_Functional_Scenario2: *level_2
  Unit_hipMemGetInfo_Functional_Scenario3: *level_2
  Unit_hipMemGetInfo_Functional_scenario4: *level_2
  Unit_hipMemGetInfo_Functional_MultiDevice_Scenario5: *level_2
  Unit_hipMemGetInfo_SetHiddenFreeMemFromChild: *level_2
  Unit_hipMemGetInfo_VerifyHiddenFreeMemForAllGpu: *level_2
  Unit_NoGpuTst_hipGetDeviceCount: *level_2
  Unit_NoGpuTst_hipSetDevice: *level_2
  Unit_NoGpuTst_hipDeviceGetAttribute: *level_2
  Unit_NoGpuTst_hipDeviceGetP2PAttribute: *level_2
  Unit_NoGpuTst_hipDeviceGetPCIBusId: *level_2
  Unit_NoGpuTst_hipDeviceGetByPCIBusId: *level_2
  Unit_NoGpuTst_hipDeviceTotalMem: *level_2
  Unit_NoGpuTst_hipFuncSetSharedMemConfig: *level_2
  Unit_NoGpuTst_hipStreamCreate: *level_2
  Unit_NoGpuTst_hipStreamCreateWithPriority: *level_2
  Unit_NoGpuTst_hipStreamSynchronize: *level_2
  Unit_NoGpuTst_hipStreamGetFlags: *level_2
  Unit_NoGpuTst_hipExtStreamCreateWithCUMask: *level_2
  Unit_NoGpuTst_hipStreamAddCallback: *level_2
  Unit_NoGpuTst_hipEventCreateWithFlags: *level_2
  Unit_NoGpuTst_hipDeviceSynchronize: *level_2
  Unit_NoGpuTst_hipGetDevice: *level_2
  Unit_NoGpuTst_hipDeviceGetCacheConfig: *level_2
  Unit_NoGpuTst_hipDeviceGetSharedMemConfig: *level_2
  Unit_NoGpuTst_hipDeviceSetSharedMemConfig: *level_2
  Unit_NoGpuTst_hipPointerGetAttributes: *level_2
  Unit_NoGpuTst_hipExtMallocWithFlags: *level_2
  Unit_NoGpuTst_hipMallocManaged: *level_2
  Unit_NoGpuTst_hipHostFree: *level_2
  Unit_NoGpuTst_hipMemcpyWithStream: *level_2
  Unit_NoGpuTst_hipMallocArray: *level_2
  Unit_NoGpuTst_hipMallocMipmappedArray: *level_2
  Unit_NoGpuTst_hipDeviceEnablePeerAccess: *level_2
  Unit_NoGpuTst_hipHostMalloc: *level_2
  Unit_NoGpuTst_hipMalloc: *level_2
  Unit_NoGpuTst_hipHostRegister: *level_2
  Unit_NoGpuTst_hipMemcpy: *level_2
  Unit_NoGpuTst_hipMemAllocPitch: *level_2
  Unit_NoGpuTst_hipMemGetInfo: *level_2
  Unit_NoGpuTst_hipMalloc3DArray: *level_2
  Unit_NoGpuTst_hipDeviceCanAccessPeer: *level_2
  Unit_NoGpuTst_hipDeviceDisablePeerAccess: *level_2
  Unit_NoGpuTst_hipDeviceGet: *level_2
  Unit_NoGpuTst_hipDeviceComputeCapability: *level_2
  Unit_NoGpuTst_hipDeviceGetName: *level_2
  Unit_NoGpuTst_hipGetDeviceProperties: *level_2
  Unit_NoGpuTst_hipChooseDevice: *level_2
  Unit_NoGpuTst_hipExtGetLinkTypeAndHopCount: *level_2
  Unit_NoGpuTst_hipExtStreamGetCUMask: *level_2
  Unit_NoGpuTst_hipFuncSetAttribute: *level_2
  Unit_NoGpuTst_hipFuncSetCacheConfig: *level_2
  Unit_NoGpuTst_hipStreamCreateWithFlags: *level_2
  Unit_NoGpuTst_hipDeviceGetStreamPriorityRange: *level_2
  Unit_NoGpuTst_hipEventCreate: *level_2
  Unit_NoGpuTst_hipStreamGetPriority: *level_2
  Unit_NoGpuTst_hipDeviceReset: *level_2
  Unit_NoGpuTst_hipDeviceSetCacheConfig: *level_2
  Unit_NoGpuTst_hipDeviceGetLimit: *level_2
  Unit_NoGpuTst_hipGetDeviceFlags: *level_2
  Unit_NoGpuTst_hipSetDeviceFlags: *level_2
  Unit_NoGpuTst_hipModuleLoad: *level_2
  Unit_NoGpuTst_hipFuncGetAttributes: *level_2
  Unit_NoGpuTst_hipModuleLoadData: *level_2
  Unit_NoGpuTst_hipModuleLoadDataEx: *level_2
  Unit_NoGpuTst_hipLaunchCooperativeKernel: *level_2
  Unit_NoGpuTst_hipLaunchCooperativeKernelMultiDevice: *level_2
  Unit_NoGpuTst_hipExtLaunchMultiKernelMultiDevice: *level_2
  Unit_NoGpuTst_hipOccupancyMaxActiveBlocksPerMultiprocessor: *level_2
  Unit_NoGpuTst_hipOccupancyMaxActiveBlocksPerMultiprocessorFlags: *level_2
  Unit_NoGpuTst_hipOccupancyMaxPotentialBlockSize: *level_2
  Unit_NoGpuTst_hiprtcVersion: *level_2
  Unit_NoGpuTst_hiprtcCreateProgram_DestroyProg: *level_2
  Unit_NoGpuTst_hiprtcAddNameExpression: *level_2
  Unit_NoGpuTst_hipMallocPitch: *level_2
  Unit_NoGpuTst_hipMipmappedArrayCreate: *level_2
  Unit_NoGpuTst_hipMalloc3D: *level_2
  Unit_NoGpuTst_hipGraphCreate: *level_2
  Unit_NoGpuTst_hipStreamBeginCapture: *level_2
  Unit_NoGpuTst_hipStreamIsCapturing: *level_2
  Unit_hipSetDevice_InvalidVisibleDeviceList: *level_2
  Unit_hipSetDevice_ValidVisibleDeviceList: *level_2
  Unit_hipSetDevice_SubsetOfAvailableDevices: *level_2
  Unit_hipSetDevice_MinRvdMaxHvdDevicesList: *level_2
  Unit_hipSetDevice_MaxRvdMinHvdDevicesList: *level_2
  Unit_hipSetDevice_RvdCvdDevicesList: *level_2
