---
perftests:
  Perf_hipPerfDotProduct: *level_2
  Perf_hipPerfMandelbrot: *level_2
  Perf_hipPerfDispatchAndExecutionSpeed: *level_2
  Unit_hipKernelLookUp_PerfTest: *level_2
  Unit_hipEventOverFlow_PerfTest: *level_2
  Perf_GraphWithMoreAllocFreeNodes_SingleBranchNoOperations: *level_2
  Perf_GraphWithMoreAllocFreeNodes_SerialNodesSingleBranchWithOps: *level_2
  Perf_GraphWithMoreAllocFreeNodes_MultipleBranches: *level_2
  Perf_GraphWithMoreAllocFreeNodes_MultipleIndependentBranches: *level_2
  Perf_GraphWithMoreAllocFreeNodes_OneBranchNoOps_AutoFreeOnLaunch: *level_2
  Unit_hipGraph_Performance_Improvement_ParallelGraph: *level_2
  Unit_hipGraph_Performance_With_Stream_Operations: *level_2
  Unit_hipGraph_Performance_With_Stream_Capture: *level_2
  Perf_GraphTopology_Straight: *level_2
  Perf_GraphTopology_Parallel: *level_2
  Perf_GraphTopology_Hexagon: *level_2
  Perf_GraphTopology_Mixed: *level_2
  Perf_hipPerfMemcpy_test: *level_2
  Perf_hipPerfBufferCopyRectSpeed_test: *level_2
  Perf_hipPerfBufferCopySpeed_test: *level_2
  Perf_hipPerfDevMemReadSpeed_test: *level_2
  Perf_hipPerfDevMemWriteSpeed_test: *level_2
  Perf_hipPerfMemFill_test: *level_2
  Perf_hipPerfMemMallocCpyFree_test: *level_2
  Perf_hipPerfMemset_test: *level_2
  Perf_hipPerfSampleRate_test: *level_2
  Perf_hipPerfSharedMemReadSpeed_test: *level_2
  Perf_hipTestP2PUniDirMemcpyAsync_test_Timing_CPU: *level_2
  Perf_hipTestP2PUniDirMemcpyAsync_test_Timing_GPU: *level_2
  Perf_hipTestP2PUniDirKernelCopy_test_Timing_CPU: *level_2
  Perf_hipTestP2PUniDirKernelCopy_test_Timing_GPU: *level_2
  Perf_hipTestP2PBiDirMemcpyAsync_test: *level_2
  Perf_hipTestP2PBiDirKernelCopy_test: *level_2
  Perf_hipCheckP2PSupport: *level_2
  Perf_PerfBufferCopySpeedAll2All_test_hipMemcpyPeerAsync_remotes_to_local: *level_2
  Perf_PerfBufferCopySpeedAll2All_test_hipMemcpyPeerAsync_local_to_remotes: *level_2
  Perf_PerfBufferCopySpeedAll2All_test_kernel_copy_remotes_to_local: *level_2
  Perf_PerfBufferCopySpeedAll2All_test_kernel_copy_local_to_remotes: *level_2
  Perf_PerfBufferCopySpeedAll2One_test_hipMemcpyPeerAsync_remotes_to_local: *level_2
  Perf_PerfBufferCopySpeedOne2All_test_hipMemcpyPeerAsync_local_to_remotes: *level_2
  Perf_PerfBufferCopySpeedAll2One_test_kernel_copy_remotes_to_local: *level_2
  Perf_PerfBufferCopySpeedOne2All_test_kernel_copy_local_to_remotes: *level_2
  Perf_MempoolManager_hipMallocAsync_hipFreeAsync: *level_2
  Unit_Perf_Device_Heap_Memory_Allocation: *level_2
  Perf_PerfBufferCopySpeedAll2All_Inter_GPU: *level_2
  Perf_hipPerfMemcpyAsyncSpeed_test: *level_2
  Perf_hipPerfMemsetAsyncSpeed_test: *level_2
  Perf_hipPerfHostNumaAlloc_test: *level_2
  Perf_hipPerfDeviceConcurrency: *level_2
  Perf_hipPerfStreamConcurrency: *level_2
  Perf_hipPerfStreamCreateCopyDestroy: *level_2
  Perf_KernelLaunchLatency_IncreasingNumberOfStreams: *level_2
  Perf_hipPerfMultiStreamKernelLaunch: *level_2
  Perf_hipPerfVMMAllocSpeed_test: *level_2
  Perf_hipPerfHostNumaAlloc_test_preferred_host_numa_node_on_each_GPU: *level_2
