---
performance:
  Performance_hipEventCreate: *level_2
  Performance_hipEventCreateWithFlags: *level_2
  Performance_hipEventRecord: *level_2
  Performance_hipEventDestroy: *level_2
  Performance_hipEventSynchronize: *level_2
  Performance_hipEventElapsedTime: *level_2
  Performance_hipEventQuery: *level_2
  Performance_Example: *level_2
  Performance_Triple_Chevron: *level_2
  Performance_hipLaunchKernel: *level_2
  Performance_hipLaunchCooperativeKernel: *level_2
  Performance_hipExtLaunchKernel: *level_2
  Performance_hipExtLaunchKernelGGL_QueryGPUFrequency:
    <<: *level_2
    # Following tests disabled as it should be a local perf test
    disabled: [amd_linux, amd_windows, amd_wsl]
  Performance_hipMemcpy_DeviceToHost: *level_2
  Performance_hipMemcpy_HostToDevice: *level_2
  Performance_hipMemcpy_HostToHost: *level_2
  Performance_hipMemcpy_DeviceToDevice_EnablePeerAccess: *level_2
  Performance_hipMemcpy_DeviceToDevice_DisablePeerAccess: *level_2
  Performance_hipMemcpyAsync_DeviceToHost: *level_2
  Performance_hipMemcpyAsync_HostToDevice: *level_2
  Performance_hipMemcpyAsync_HostToHost: *level_2
  Performance_hipMemcpyAsync_DeviceToDevice_DisablePeerAccess: *level_2
  Performance_hipMemcpyAsync_DeviceToDevice_EnablePeerAccess: *level_2
  Performance_hipMemcpyWithStream_DeviceToHost: *level_2
  Performance_hipMemcpyWithStream_HostToDevice: *level_2
  Performance_hipMemcpyWithStream_HostToHost: *level_2
  Performance_hipMemcpyWithStream_DeviceToDevice_DisablePeerAccess: *level_2
  Performance_hipMemcpyWithStream_DeviceToDevice_EnablePeerAccess: *level_2
  Performance_hipMemcpyAtoH:
    <<: *level_2
    tags: [image]
  Performance_hipMemcpyHtoA:
    <<: *level_2
    tags: [image]
  Performance_hipMemcpyDtoD_PeerAccessEnabled: *level_2
  Performance_hipMemcpyDtoD_PeerAccessDisabled: *level_2
  Performance_hipMemcpyDtoDAsync_PeerAccessEnabled: *level_2
  Performance_hipMemcpyDtoDAsync_PeerAccessDisabled: *level_2
  Performance_hipMemcpyDtoH: *level_2
  Performance_hipMemcpyDtoHAsync: *level_2
  Performance_hipMemcpyHtoD: *level_2
  Performance_hipMemcpyHtoDAsync: *level_2
  Performance_hipMemcpyHtoDKernelDtoHV1Async: *level_2
  Performance_hipMemcpyHtoDKernelDtoHV2Async: *level_2
  Performance_hipMemcpyToSymbol_SingularValue: *level_2
  Performance_hipMemcpyToSymbol_ArrayValue: *level_2
  Performance_hipMemcpyToSymbol_WithOffset: *level_2
  Performance_hipMemcpyToSymbolAsync_SingularValue: *level_2
  Performance_hipMemcpyToSymbolAsync_ArrayValue: *level_2
  Performance_hipMemcpyToSymbolAsync_WithOffset: *level_2
  Performance_hipMemcpyFromSymbol_SingularValue: *level_2
  Performance_hipMemcpyFromSymbol_ArrayValue: *level_2
  Performance_hipMemcpyFromSymbol_WithOffset: *level_2
  Performance_hipMemcpyFromSymbolAsync_SingularValue: *level_2
  Performance_hipMemcpyFromSymbolAsync_ArrayValue: *level_2
  Performance_hipMemcpyFromSymbolAsync_WithOffset: *level_2
  Performance_hipMemcpy2D_DeviceToHost: *level_2
  Performance_hipMemcpy2D_HostToDevice: *level_2
  Performance_hipMemcpy2D_HostToHost:
    <<: *level_2
    # Below tests are failing PSDB
    disabled: [amd_windows]
  Performance_hipMemcpy2D_DeviceToDevice_DisablePeerAccess: *level_2
  Performance_hipMemcpy2D_DeviceToDevice_EnablePeerAccess: *level_2
  Performance_hipMemcpy2DAsync_DeviceToHost: *level_2
  Performance_hipMemcpy2DAsync_HostToDevice: *level_2
  Performance_hipMemcpy2DAsync_HostToHost:
    <<: *level_2
    # Below tests are failing PSDB
    disabled: [amd_windows]
  Performance_hipMemcpy2DAsync_DeviceToDevice_DisablePeerAccess: *level_2
  Performance_hipMemcpy2DAsync_DeviceToDevice_EnablePeerAccess: *level_2
  Performance_hipMemcpy2DToArray_HostToDevice:
    <<: *level_2
    tags: [image]
  Performance_hipMemcpy2DToArray_DeviceToDevice_DisablePeerAccess:
    <<: *level_2
    tags: [image]
  Performance_hipMemcpy2DToArray_DeviceToDevice_EnablePeerAccess:
    <<: *level_2
    tags: [image]
  Performance_hipMemcpy2DToArrayAsync_HostToDevice:
    <<: *level_2
    tags: [image]
  Performance_hipMemcpy2DToArrayAsync_DeviceToDevice_DisablePeerAccess:
    <<: *level_2
    tags: [image]
  Performance_hipMemcpy2DToArrayAsync_DeviceToDevice_EnablePeerAccess:
    <<: *level_2
    tags: [image]
  Performance_hipMemcpy2DFromArray_DeviceToHost:
    <<: *level_2
    tags: [image]
  Performance_hipMemcpy2DFromArray_DeviceToDevice_DisablePeerAccess:
    <<: *level_2
    tags: [image]
  Performance_hipMemcpy2DFromArray_DeviceToDevice_EnablePeerAccess:
    <<: *level_2
    tags: [image]
  Performance_hipMemcpy2DFromArrayAsync_DeviceToHost:
    <<: *level_2
    tags: [image]
  Performance_hipMemcpy2DFromArrayAsync_DeviceToDevice_DisablePeerAccess:
    <<: *level_2
    tags: [image]
  Performance_hipMemcpy2DFromArrayAsync_DeviceToDevice_EnablePeerAccess:
    <<: *level_2
    tags: [image]
  Performance_hipMemcpyParam2D_DeviceToHost: *level_2
  Performance_hipMemcpyParam2D_HostToDevice: *level_2
  Performance_hipMemcpyParam2D_HostToHost: *level_2
  Performance_hipMemcpyParam2D_DeviceToDevice_DisablePeerAccess: *level_2
  Performance_hipMemcpyParam2D_DeviceToDevice_EnablePeerAccess: *level_2
  Performance_hipMemcpyParam2DAsync_DeviceToHost: *level_2
  Performance_hipMemcpyParam2DAsync_HostToDevice: *level_2
  Performance_hipMemcpyParam2DAsync_HostToHost: *level_2
  Performance_hipMemcpyParam2DAsync_DeviceToDevice_DisablePeerAccess: *level_2
  Performance_hipMemcpyParam2DAsync_DeviceToDevice_EnablePeerAccess: *level_2
  Performance_hipMemcpy3D_DeviceToHost: *level_2
  Performance_hipMemcpy3D_HostToDevice: *level_2
  Performance_hipMemcpy3D_HostToHost: *level_2
  Performance_hipMemcpy3D_DeviceToDevice_DisablePeerAccess: *level_2
  Performance_hipMemcpy3D_DeviceToDevice_EnablePeerAccess: *level_2
  Performance_hipMemcpy3DAsync_DeviceToHost: *level_2
  Performance_hipMemcpy3DAsync_HostToDevice: *level_2
  Performance_hipMemcpy3DAsync_HostToHost: *level_2
  Performance_hipMemcpy3DAsync_DeviceToDevice_DisablePeerAccess: *level_2
  Performance_hipMemcpy3DAsync_DeviceToDevice_EnablePeerAccess: *level_2
  Performance_hipMemset: *level_2
  Performance_hipMemsetAsync: *level_2
  Performance_hipMemsetD8: *level_2
  Performance_hipMemsetD8Async: *level_2
  Performance_hipMemsetD16:
    <<: *level_2
    # Below tests tests fail in PSDB
    disabled: [nvidia_windows]
  Performance_hipMemsetD16Async:
    <<: *level_2
    # Below tests tests fail in PSDB
    disabled: [nvidia_windows]
  Performance_hipMemsetD32:
    <<: *level_2
    # Below tests tests fail in PSDB
    disabled: [nvidia_windows]
  Performance_hipMemsetD32Async:
    <<: *level_2
    # Below tests tests fail in PSDB
    disabled: [nvidia_windows]
  Performance_hipMemset2D: *level_2
  Performance_hipMemset2DAsync: *level_2
  Performance_hipMemset3D: *level_2
  Performance_hipMemset3DAsync: *level_2
  Performance_hipStreamWaitEvent: *level_2
  Performance_hipStreamGetFlags: *level_2
  Performance_hipStreamGetPriority: *level_2
  Performance_hipExtStreamCreateWithCUMask: *level_2
  Performance_hipExtStreamGetCUMask: *level_2
  Performance_hipStreamAddCallback: *level_2
  Performance_hipStreamWaitValue32: *level_2
  Performance_hipStreamWaitValue64: *level_2
  Performance_hipStreamWriteValue32: *level_2
  Performance_hipStreamWriteValue64: *level_2
  Performance_hipMallocAsync: *level_2
  Performance_hipFreeAsync: *level_2
  Performance_hipMemPoolCreate: *level_2
  Performance_hipMemPoolDestroy: *level_2
  Performance_hipMemPoolTrimTo: *level_2
  Performance_hipMemPoolSetAttribute: *level_2
  Performance_hipMemPoolGetAttribute: *level_2
  Performance_hipMemPoolSetAccess: *level_2
  Performance_hipMallocFromPoolAsync: *level_2
  Performance_hipMemPoolExportToShareableHandle: *level_2
  Performance_hipMemPoolGetAccess: *level_2
  Performance_hipMemPoolImportFromShareableHandle: *level_2
  Performance_hipMemPoolExportPointer: *level_2
  Performance_hipMemPoolImportPointer: *level_2
  Performance_hipStreamCreate: *level_2
  Performance_hipStreamCreateWithFlags: *level_2
  Performance_hipStreamCreateWithPriority: *level_2
  Performance_hipStreamDestroy: *level_2
  Performance_hipDeviceGetStreamPriorityRange: *level_2
  Performance_hipStreamQuery: *level_2
  Performance_hipStreamSynchronize: *level_2
  Performance_Reduce_Sync_Add: *level_2
  Performance_Reduce_Sync_Min: *level_2
  Performance_Reduce_Sync_Max: *level_2
  Performance_Reduce_Sync_And: *level_2
  Performance_Reduce_Sync_Or: *level_2
  Performance_Reduce_Sync_Xor: *level_2
