---
stress:
  Stress_deviceAllocation_malloc_Even: *level_2
  Stress_deviceAllocation_malloc_Odd: *level_2
  Stress_deviceAllocation_new_Even: *level_2
  Stress_deviceAllocation_new_Odd: *level_2
  Stress_deviceAllocation_malloc_hipmallocmanaged: *level_2
  Stress_deviceAllocation_new_hipmallocmanaged: *level_2
  Stress_deviceAllocation_malloc_hipmalloc: *level_2
  Stress_deviceAllocation_new_hipmalloc: *level_2
  Stress_deviceAllocation_Negative: *level_2
  Stress_deviceAllocation_malloc_loop_singlekernel: *level_2
  Stress_deviceAllocation_new_loop_singlekernel: *level_2
  Stress_deviceAllocation_malloc_loop_multkernel: *level_2
  Stress_deviceAllocation_new_loop_multkernel: *level_2
  Stress_hipMalloc:
    <<: *level_2
    tags: [DifferentSizes]
  Stress_hipMemcpy_multiDevice_AllAPIs: *level_2
  Stress_hipMallocManaged_MultiSize: *level_2
  Stress_hipMallocManaged_KrnlWth2MemTypes: *level_2
  Stress_hipMallocManaged_MultiKrnlHmmAccess: *level_2
  Stress_hipMallocManaged_ExtremeSizes: *level_2
  Stress_hipMemPrefetchAsyncOneToAll: *level_2
  Stress_hipHostMalloc_MaxAllocation: *level_2
  Stress_hipHostMalloc_MaxAllocation_AllGpu: *level_2
  Stress_hipHostRegister_Oversubscription: *level_2
  Stress_hipMalloc_HighSizeAlloc: *level_2
  Stress_HMM_OverSubscriptionTst: *level_2
  Stress_hipModuleLoadUnload: *level_2
  Stress_printf_ComplexKernelMultStream: *level_2
  Stress_printf_ComplexKernelMultStreamMultGpu: *level_2
  Stress_printf_ConstStr: *level_2
  Stress_printf_IfElseConditionalStr: *level_2
  Stress_printf_IfConditionalStr: *level_2
  Stress_printf_VariableStr: *level_2
  Stress_printf_DependentCalc: *level_2
  Stress_printf_DecimalStr: *level_2
  Stress_printf_SharedMem: *level_2
  Stress_printf_SynchronizedPrintf: *level_2
  Stress_printf_AtomicCalc: *level_2
  Stress_hipStreamCreate_SyncTest: *level_2
  Stress_hipStreamCreatePriority_SyncTest: *level_2
  Stress_hipStreamCreateWithFlags_SyncTest: *level_2
  Stress_StreamEnqueue_DifferentThreads: *level_2
  Stress_StreamEnqueue_DifferentThreads_MultiGPU: *level_2
  Stress_hipMalloc_LoopRegressionAllocFreeCycles: *level_2
  Stress_hipMalloc_AllocateAndPoolBuffers: *level_2
  Stress_hipMalloc_Multithreaded_MultiGPU:
    <<: *level_2
    tags: [multigpu]
