---
assertion:
  Unit_StaticAssert_Positive_Basic_RTC:
    <<: *level_2
    # Below tests fail in external CI for PR https://github.com/ROCm-Developer-Tools/hip-tests/pull/210
    disabled: [amd_windows]
    tags: [deviceLib]
  Unit_StaticAssert_Negative_Basic_RTC:
    <<: *level_2
    tags: [deviceLib]
  Unit_Assert_Positive_Basic_KernelPass: *level_2
  Unit_Assert_Positive_Basic_KernelFail:
    <<: *level_2
    # === Below tests fail in external CI for PR https://github.com/ROCm-Developer-Tools/hip-tests/pull/210 ===
    disabled: [amd_windows]
