---
callback:
  Unit_hipApiName_Positive_Basic: *level_2
  Unit_hipApiName_Negative_ReservedIds: *level_2
  Unit_hipGetStreamDeviceId_Positive_Threaded_Basic: *level_2
  Unit_hipGetStreamDeviceId_Positive_Multithreaded_Basic:
    <<: *level_2
    tags: []
  Unit_hipGetStreamDeviceId_Negative_Parameters: *level_2
  Unit_hipKernelNameRef_Positive_Basic:
    <<: *level_2
    # (amd_windows) Note: intermittent Seg fault failure
    # (amd_wsl) Note: intermittent Seg fault failure
    disabled: [amd_windows, amd_wsl]
  Unit_hipKernelNameRef_Negative_Parameters:
    <<: *level_2
    # (amd_windows) Note: intermittent Seg fault failure
    # (amd_wsl) Note: intermittent Seg fault failure
    # (amd_wsl) Note: Linux disabled
    disabled: [amd_windows, amd_wsl]
  Unit_hipKernelNameRefByPtr_Positive_Basic: *level_2
  Unit_hipKernelNameRefByPtr_Positive_StreamNullptr: *level_2
  Unit_hipKernelNameRefByPtr_Negative_KernelNullptr: *level_2
