---
complex:
  Unit_Device_Complex_Unary_Device_Sanity_Positive:
    <<: *level_2
    tags: [deviceLib, types]
  Unit_Device_Complex_Unary_Host_Sanity_Positive:
    <<: *level_2
    tags: [deviceLib, types]
  Unit_Device_Complex_Binary_Device_Sanity_Positive:
    <<: *level_2
    tags: [deviceLib, types]
  Unit_Device_Complex_Binary_Host_Sanity_Positive:
    <<: *level_2
    tags: [deviceLib, types]
  Unit_Device_Complex_hipCfma_Device_Sanity_Positive:
    <<: *level_2
    tags: [deviceLib, types]
  Unit_Device_Complex_hipCfma_Host_Sanity_Positive:
    <<: *level_2
    tags: [deviceLib, types]
  Unit_Device_make_Complex_Device_Positive:
    <<: *level_2
    tags: [deviceLib, types]
  Unit_Device_make_Complex_Host_Positive:
    <<: *level_2
    tags: [deviceLib, types]
  Unit_Device_make_hipComplex_Device_Positive: *level_2
  Unit_Device_make_hipComplex_Host_Positive: *level_2
  Unit_Device_Complex_Cast_Device_Sanity_Positive:
    <<: *level_2
    tags: [deviceLib, types]
  Unit_Device_Complex_Cast_Host_Sanity_Positive:
    <<: *level_2
    tags: [deviceLib, types]
  Unit_Device_Complex_Constructor_Host:
    <<: *level_2
    tags: [deviceLib, types]
