---
dynamicLoading:
  Unit_dynamic_loading_device_kernels_from_library:
    <<: *level_2
    # Rock_Linux_Failures_on_gfx94X
    disabled: [amd_linux]
    tags: [module]
  Unit_hipApiDynamicLoad_hipGetProcAddress:
    <<: *level_2
    tags: [module]
  Unit_hipApiDynamicLoad:
    <<: *level_2
    tags: [module]
  Unit_hipGetProcAddress_Positive:
    <<: *level_2
    tags: [module]
    disabled: [amd_wsl]
  Unit_hipGetProcAddress_Negative:
    <<: *level_2
    tags: [module]
    disabled: [amd_wsl]
  Unit_hipGetProcAddress_spt_Positive:
    <<: *level_2
    tags: [module]
    disabled: [amd_wsl]
  Unit_hipGetProcAddress_spt_Negative:
    <<: *level_2
    tags: [module]
    disabled: [amd_wsl]
  Unit_hipGetProcAddress_hipGetProcAddress_spt_CheckAddress:
    <<: *level_2
    tags: [module]
    disabled: [amd_wsl]
  Unit_hipGetProcAddress_With_spt_CompilerOption:
    <<: *level_2
    tags: [module]
    disabled: [amd_wsl]
