---
multiThread:
  Unit_hipMemsetAsync_QueueJobsMultithreaded:
    <<: *level_2
    tags: [memory]
  Unit_hipMultiThreadDevice_Streams:
    <<: *level_2
    tags: [device_mgmt]
  Unit_hipMultiThreadDevice_SerialPyramid:
    <<: *level_2
    # Rock_Linux_Failures_on_gfx94X
    disabled: [amd_linux]
    tags: [device_mgmt]
  Unit_hipMultiThreadDevice_ParallelPyramid:
    <<: *level_2
    tags: [device_mgmt]
  Unit_hipMultiThreadDevice_NearZero:
    <<: *level_2
    # Note: Windows disabled
    disabled: [amd_windows, amd_wsl]
    tags: [device_mgmt]
  Unit_hipMultiThreadStreams1_AsyncSync:
    <<: *level_2
    tags: [stream]
  Unit_hipMultiThreadStreams1_AsyncAsync:
    <<: *level_2
    tags: [stream]
  Unit_hipMultiThreadStreams1_AsyncSame:
    <<: *level_2
    tags: [stream]
  Unit_hipMultiThreadStreams2:
    <<: *level_2
    tags: [stream]
