---
vulkan_interop:
  Unit_hipDestroyExternalMemory_Vulkan_Negative_Parameters: *level_2
  Unit_hipDestroyExternalMemory_Vulkan_Capture: *level_2
  Unit_hipDestroyExternalSemaphore_Vulkan_Negative_Parameters: *level_2
  Unit_hipDestroyExternalSemaphore_Vulkan_Capture: *level_2
  Unit_hipExternalMemoryGetMappedBuffer_Vulkan_Positive_Read_Write: *level_2
  Unit_hipExternalMemoryGetMappedBuffer_Vulkan_Positive_Read_Write_With_Offset: *level_2
  Unit_hipExternalMemoryGetMappedBuffer_Vulkan_Negative_Parameters: *level_2
  Unit_hipExternalMemoryGetMappedBuffer_Vulkan_Capture: *level_2
  Unit_hipExternalMemoryGetMappedBuffer_Vulkan_Positive_Read_Write_Device_Memory: *level_2
  Unit_hipExternalMemoryGetMappedBuffer_Vulkan_Positive_Read_Write_With_Offset_Device_Memory: *level_2
  Unit_hipExternalMemoryGetMappedMipmappedArray_Vulkan_Positive_Read_Write: *level_2
  Unit_hipExternalMemoryGetMappedMipmappedArray_Vulkan_Array_Layered: *level_2
  Unit_hipExternalMemoryGetMappedMipmappedArray_Vulkan_Array_Cubemap: *level_2
  Unit_hipExternalMemoryGetMappedMipmappedArray_Vulkan_Negative_Parameters: *level_2
  Unit_hipExternalMemoryGetMappedMipmappedArray_Vulkan_Capture: *level_2
  Unit_hipGraphAddExternalSemaphoresSignalNode_Positive_Basic: *level_2
  Unit_hipGraphAddExternalSemaphoresSignalNode_Vulkan_Positive_Timeline_Semaphore: *level_2
  Unit_hipGraphAddExternalSemaphoresSignalNode_Vulkan_Positive_Multiple_Semaphores: *level_2
  Unit_hipGraphAddExternalSemaphoresSignalNode_Vulkan_Negative_Parameters: *level_2
  Unit_hipGraphAddExternalSemaphoresWaitNode_Positive_Basic: *level_2
  Unit_hipGraphAddExternalSemaphoresWaitNode_Vulkan_Positive_Timeline_Semaphore: *level_2
  Unit_hipGraphAddExternalSemaphoresWaitNode_Vulkan_Positive_Multiple_Semaphores: *level_2
  Unit_hipGraphAddExternalSemaphoresWaitNode_Vulkan_Negative_Parameters: *level_2
  Unit_hipGraphExecExternalSemaphoresSignalNodeSetParams_Positive_Basic: *level_2
  Unit_hipGraphExecExternalSemaphoresSignalNodeSetParams_Vulkan_Positive_Timeline_Semaphore: *level_2
  Unit_hipGraphExecExternalSemaphoresSignalNodeSetParams_Vulkan_Positive_Multiple_Semaphores: *level_2
  Unit_hipGraphExecExternalSemaphoresSignalNodeSetParams_Vulkan_Negative_Parameters: *level_2
  Unit_hipGraphExecExternalSemaphoresWaitNodeSetParams_Positive_Basic: *level_2
  Unit_hipGraphExecExternalSemaphoresWaitNodeSetParams_Vulkan_Positive_Timeline_Semaphore: *level_2
  Unit_hipGraphExecExternalSemaphoresWaitNodeSetParams_Vulkan_Positive_Multiple_Semaphores: *level_2
  Unit_hipGraphExecExternalSemaphoresWaitNodeSetParams_Vulkan_Negative_Parameters: *level_2
  Unit_hipGraphExternalSemaphoresSignalNodeGetParams_Negative_Parameters: *level_2
  Unit_hipGraphExternalSemaphoresSignalNodeSetParams_Positive_Basic: *level_2
  Unit_hipGraphExternalSemaphoresSignalNodeSetParams_Vulkan_Positive_Timeline_Semaphore: *level_2
  Unit_hipGraphExternalSemaphoresSignalNodeSetParams_Vulkan_Positive_Multiple_Semaphores: *level_2
  Unit_hipGraphExternalSemaphoresSignalNodeSetParams_Vulkan_Negative_Parameters: *level_2
  Unit_hipGraphExternalSemaphoresWaitNodeGetParams_Negative_Parameters: *level_2
  Unit_hipGraphExternalSemaphoresWaitNodeSetParams_Positive_Basic: *level_2
  Unit_hipGraphExternalSemaphoresWaitNodeSetParams_Vulkan_Positive_Timeline_Semaphore: *level_2
  Unit_hipGraphExternalSemaphoresWaitNodeSetParams_Vulkan_Positive_Multiple_Semaphores: *level_2
  Unit_hipGraphExternalSemaphoresWaitNodeSetParams_Vulkan_Negative_Parameters: *level_2
  Unit_hipImportExternalMemory_Vulkan_Negative_Parameters: *level_2
  Unit_hipImportExternalMemory_Vulkan_Capture: *level_2
  Unit_hipImportExternalSemaphore_Vulkan_Negative_Parameters: *level_2
  Unit_hipImportExternalSemaphore_Vulkan_Capture: *level_2
  Unit_hipSignalExternalSemaphoresAsync_Vulkan_Positive_Binary_Semaphore: *level_2
  Unit_hipSignalExternalSemaphoresAsync_Vulkan_Positive_Timeline_Semaphore: *level_2
  Unit_hipSignalExternalSemaphoresAsync_Vulkan_Positive_Multiple_Semaphores: *level_2
  Unit_hipSignalExternalSemaphoresAsync_Vulkan_Negative_Parameters: *level_2
  Unit_hipWaitExternalSemaphoresAsync_Vulkan_Positive_Binary_Semaphore: *level_2
  Unit_hipWaitExternalSemaphoresAsync_Vulkan_Positive_Timeline_Semaphore: *level_2
  Unit_hipWaitExternalSemaphoresAsync_Vulkan_Positive_Multiple_Semaphores: *level_2
  Unit_hipWaitExternalSemaphoresAsync_Vulkan_Negative_Parameters: *level_2
